# permissions for end users to edit clustertopologies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustertopology-editor-role
rules:
- apiGroups:
  - edge.fdse.lab
  resources:
  - clustertopologies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - edge.fdse.lab
  resources:
  - clustertopologies/status
  verbs:
  - get
